# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1207, 915)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(290, 50, 231, 192))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(49)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(360, 250, 101, 31))
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(70, 310, 751, 491))
        self.graphicsView.setObjectName("graphicsView")
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(270, 10, 441, 31))
        self.lblTtitulo.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo.setObjectName("lblTtitulo")
        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(90, 120, 181, 31))
        self.lblTtitulo_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")
        self.lblTtitulo2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo2.setGeometry(QtCore.QRect(90, 330, 181, 71))
        self.lblTtitulo2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo2.setText("")
        self.lblTtitulo2.setPixmap(QtGui.QPixmap("logo_eafit_blanco.png"))
        self.lblTtitulo2.setObjectName("lblTtitulo2")
        self.btnMatriz3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMatriz3.setGeometry(QtCore.QRect(970, 400, 111, 31))
        self.btnMatriz3.setObjectName("btnMatriz3")
        self.btnMatriz2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMatriz2.setEnabled(True)
        self.btnMatriz2.setGeometry(QtCore.QRect(970, 50, 111, 31))
        self.btnMatriz2.setObjectName("btnMatriz2")
        self.tblMatriz2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tblMatriz2.setGeometry(QtCore.QRect(920, 140, 231, 192))
        self.tblMatriz2.setShowGrid(True)
        self.tblMatriz2.setRowCount(4)
        self.tblMatriz2.setColumnCount(4)
        self.tblMatriz2.setObjectName("tblMatriz2")
        self.tblMatriz2.horizontalHeader().setDefaultSectionSize(50)
        self.tblMatriz3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tblMatriz3.setGeometry(QtCore.QRect(910, 480, 231, 192))
        self.tblMatriz3.setShowGrid(True)
        self.tblMatriz3.setRowCount(4)
        self.tblMatriz3.setColumnCount(4)
        self.tblMatriz3.setObjectName("tblMatriz3")
        self.tblMatriz3.horizontalHeader().setDefaultSectionSize(50)
        self.tblMatriz = QtWidgets.QTableWidget(self.centralwidget)
        self.tblMatriz.setGeometry(QtCore.QRect(630, 70, 231, 192))
        self.tblMatriz.setShowGrid(True)
        self.tblMatriz.setRowCount(4)
        self.tblMatriz.setColumnCount(4)
        self.tblMatriz.setObjectName("tblMatriz")
        self.tblMatriz.horizontalHeader().setDefaultSectionSize(50)
        self.lblAdyacencia = QtWidgets.QLabel(self.centralwidget)
        self.lblAdyacencia.setGeometry(QtCore.QRect(640, 20, 221, 31))
        self.lblAdyacencia.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblAdyacencia.setObjectName("lblAdyacencia")
        self.lblAdyacencia2 = QtWidgets.QLabel(self.centralwidget)
        self.lblAdyacencia2.setGeometry(QtCore.QRect(960, 90, 151, 31))
        self.lblAdyacencia2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblAdyacencia2.setObjectName("lblAdyacencia2")
        self.lblAdyacencia3 = QtWidgets.QLabel(self.centralwidget)
        self.lblAdyacencia3.setGeometry(QtCore.QRect(950, 440, 151, 31))
        self.lblAdyacencia3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblAdyacencia3.setObjectName("lblAdyacencia3")
        self.btnMatriz2.raise_()
        self.tableWidget.raise_()
        self.btnPintarGrafo.raise_()
        self.graphicsView.raise_()
        self.lblTtitulo.raise_()
        self.lblTtitulo_3.raise_()
        self.lblTtitulo2.raise_()
        self.btnMatriz3.raise_()
        self.tblMatriz2.raise_()
        self.tblMatriz3.raise_()
        self.tblMatriz.raise_()
        self.lblAdyacencia.raise_()
        self.lblAdyacencia2.raise_()
        self.lblAdyacencia3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnPintarGrafo.clicked.connect(self.btnMatriz2.show) # type: ignore
        self.btnMatriz2.clicked.connect(self.tblMatriz2.show) # type: ignore
        self.btnMatriz3.clicked.connect(self.tblMatriz3.show) # type: ignore
        self.btnMatriz2.clicked.connect(self.btnMatriz3.show) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.tblMatriz2.hide) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.btnMatriz3.hide) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.tblMatriz3.hide) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.tblMatriz.show) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.lblAdyacencia.show) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.lblAdyacencia2.hide) # type: ignore
        self.btnPintarGrafo.clicked.connect(self.lblAdyacencia3.hide) # type: ignore
        self.btnMatriz2.clicked.connect(self.lblAdyacencia2.show) # type: ignore
        self.btnMatriz3.clicked.connect(self.lblAdyacencia3.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.lblTtitulo.setText(_translate("MainWindow", "Grafos por Nicolás Ospina"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos:"))
        self.btnMatriz3.setText(_translate("MainWindow", "Matriz cúbica"))
        self.btnMatriz2.setText(_translate("MainWindow", "Matriz cuadrada"))
        self.lblAdyacencia.setText(_translate("MainWindow", "Tabla de adyacencia"))
        self.lblAdyacencia2.setText(_translate("MainWindow", "Tabla de A^2"))
        self.lblAdyacencia3.setText(_translate("MainWindow", "Tabla de A^3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
